---
title: "Games Night"
author: "By Alex Dolphin"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
library(data.table)
library(flexdashboard)
library(ggplot2)
library(magrittr)
library(RMySQL)
library(shiny)

games <- c("fifa", "rps", "headers_and_volleys", "ticket_to_ride", "catan", "ctr")
source("get_data.R")
```


Main
=======================================================================

Sidebar {.sidebar}
-----------------------------------------------------------------------

```{r main_selectors}
events_selector <- setNames(df_events$event_id, df_events$event_name)

shiny::selectInput("selected_event", "Select event", choices = events_selector, multiple = FALSE)
```

Row {.tabset}
-----------------------------------------------------------------------

```{r output_results, message=FALSE, warning=FALSE, include=FALSE}
lapply(games, function(game){
    output[[game]] <- renderDataTable({
        results[[game]][df_players, on="player_id"][event_id == input$selected_event][order(-event_points)][,-c("event_id", "player_id")]
    })
})
```

### Overview

```{r final_results}
output$final_results_plot <- renderPlot({
    plot_data <- final_results[event_id == input$selected_event]
    ggplot(plot_data, aes(x=as.factor(player_id), y=event_points, fill=game_name)) +
        geom_bar(stat = "identity", position = "stack") +
        theme_bw() +
        labs(x="Player", y="Points", fill="Game")
})
plotOutput("final_results_plot")
```


### FIFA

```{r fifa_results}
dataTableOutput("fifa")
```

### Headers and Volleys

```{r headers_and_volleys_results}
dataTableOutput("headers_and_volleys")
```

### Catan

```{r catan_results}
dataTableOutput("catan")
```

### CTR

```{r ctr_results}
dataTableOutput("ctr")
```

### Ticket to Ride

```{r ticket_to_ride_results}
dataTableOutput("ticket_to_ride")
```

### Rock Paper Scissors

```{r rps_results}
dataTableOutput("rps")
```

Update Results
=======================================================================

Sidebar {.sidebar}
-----------------------------------------------------------------------

Please select your event from the main tab

```{r update_results}
actionButton("update_results", label="Submit new results", icon("refresh"))

shiny::observeEvent(input$update_results, {
      withProgress(message = 'Creating event', value = 0.5, {})
      shiny::showNotification("Results updated!")
})
```


Row {.tabset}
-----------------------------------------------------------------------

### FIFA

### Headers and Volleys

### Catan

### CTR

### Ticket to Ride

### Rock Paper Scissors

Admin
=======================================================================

Sidebar {.sidebar}
-----------------------------------------------------------------------

```{r admin_panel}
# New user
shiny::textInput("new_user_first_name", "New user first name", value="Mr")
shiny::textInput("new_user_last_name", "New user last name", value="Chips")
shiny::actionButton("submit_new_user", label="Create new user", icon("refresh"))

## Observe player creation event
shiny::observeEvent(input$submit_new_user, {
    if(nchar(input$new_user_first_name) >= 1 & nchar(input$new_user_last_name) >= 1){
        withProgress(message = 'Creating user', value = 0.5,
            {
                create_user(input$new_user_first_name, input$new_user_last_name)
                shiny::showNotification(
                    paste0("User '",input$new_user_first_name, " ", input$new_user_last_name,"' created!")
                )
            }
        )
    }
    else {shiny::showNotification("Name is too short!")}
})

# New event
players_selector <- setNames(df_players$player_id, paste(df_players$first_name, df_players$last_name))

shiny::textInput("new_event_name", "New event name", value="Party")
shiny::selectInput(
    "new_event_players",
    "Select event players",
    choices = players_selector,
    multiple = TRUE
)
shiny::actionButton("submit_new_event", label="Create new event", icon("refresh"))

## Observe event creation event
shiny::observeEvent(input$submit_new_event, {
    if(length(input$new_event_players > 1)){
        withProgress(message = 'Creating event', value = 0.5,
            {
                create_event(input$new_event_name, input$new_event_players)
                shiny::showNotification(paste0("Event '", input$new_event_name,"' created!"))
            }
        )
    }
    else {shiny::showNotification("Too few players!")}
})
```

