---
title: "Games Night"
author: "By Alex Dolphin"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
library(data.table)
library(flexdashboard)
library(ggplot2)
library(magrittr)
library(RMySQL)
library(shiny)

games <- c("fifa", "rps", "headers_and_volleys", "ticket_to_ride", "catan", "ctr")
source("get_data.R")
```


Summary
=======================================================================

Sidebar {.sidebar}
-----------------------------------------------------------------------

```{r main_selectors}
events_selector <- setNames(df_events$event_id, df_events$event_name)

shiny::selectInput("selected_event", "Select event", choices = events_selector, multiple = FALSE)
```

Row {.tabset}
-----------------------------------------------------------------------

```{r output_results, message=FALSE, warning=FALSE, include=FALSE}
lapply(games, function(game){
    output[[game]] <- renderTable({
        results[[game]][df_players, on="player_id"][event_id == input$selected_event][order(-event_points)][,-c("event_id", "player_id", "first_name", "last_name")]
    })
})
```

### Overview

```{r final_results}
output$final_results_plot <- plotly::renderPlotly({
    if(nrow(final_results) > 0){
        plot_data <- final_results[event_id == input$selected_event]
        g <- ggplot(plot_data, aes(x=full_name, y=event_points, fill=game_name)) +
            geom_bar(stat = "identity", position = "stack") +
            theme_bw() +
            labs(x="Player", y="Points", fill="Game") +
            scale_y_continuous(breaks = seq(0, 1000, by = 1))
        plotly::ggplotly(g)
    }
})
plotly::plotlyOutput("final_results_plot")
```


### FIFA

```{r fifa_results}
tableOutput("fifa")
```

### Headers and Volleys

```{r headers_and_volleys_results}
tableOutput("headers_and_volleys")
```

### Catan

```{r catan_results}
tableOutput("catan")
```

### CTR

```{r ctr_results}
tableOutput("ctr")
```

### Ticket to Ride

```{r ticket_to_ride_results}
tableOutput("ticket_to_ride")
```

### Rock Paper Scissors

```{r rps_results}
tableOutput("rps")
```